# This is a basic workflow that is manually triggered

name: Basic workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      target_action:
        type: choice
        description: 'Action to execute'
        default: "Uno"
        options:
        - "Uno"
        - "Dos"
        - "Tres"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Simulate-Work:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16    
    - name: Checkout
      uses: actions/checkout@v3
      with:      
        access_token: ${{ github.token }}
    - name : Precheck
      shell: bash
      continue-on-error: true
      run: |
        echo "Starting precheck"      
        cancelJob=false
        if ( ! ${{github.workspace}}/.github/scripts/precheck.sh ); then
          echo "Command FAILED"
          cancelJob=true
        fi
        echo "cancelJob=$cancelJob" >> $GITHUB_ENV
        echo "Precheck Completed"
    - name : Env Setup
      run: |
        echo "Cancel Job: $cancelJob"
        if [ "$cancelJob" = true ] ; then
          echo "Cancel the job"
          npm install
          node cancel-current-workflow-run.js ${{ github.token }}
        fi