# This is a basic workflow that is manually triggered

name: Basic workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      target_action:
        type: choice
        description: 'Action to execute'
        default: "Uno"
        options:
        - "Uno"
        - "Dos"
        - "Tres"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Simulate-Work:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16    
    - name: Cancel Previous Runs
      uses: rzmudzin/cancel-workflow-action@main
      with:
        selected_target: ${{ github.event.inputs.target_action }}      
    - name: Checkout
      uses: actions/checkout@v3
      with:      
        access_token: ${{ github.token }}
    -name : Env Setup
      run: |
      echo "Token: ${{ github.token }}"
      node --version
      npm --version
    - name: Simulate Work
      run: |
        echo "Action Requested: ${{ github.event.inputs.target_action }}"
        pwd
        ls -lah
        echo "Searching for script files"
        find . -name simulate-work.sh
        echo "Search Complete"
        ${{github.workspace}}/.github/scripts/simulate-work.sh
